apiVersion: v1
kind: Service
#public service for postgres wire protocol
metadata:
  name: {{ .Chart.Name }}-public-service
  annotations:
    argocd.argoproj.io/sync-wave: "-21"
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    name: {{ (index .Values.postgresProtocolGateway.ports 0).name }}
    port: {{ (index .Values.postgresProtocolGateway.ports 0).port }}
    targetPort: {{ (index .Values.postgresProtocolGateway.ports 0).containerPort }}
  type: LoadBalancer