apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      name: {{ .Values.httpsServer.ports.name }}
      port: {{ .Values.httpsServer.ports.port }}
      targetPort: {{ .Values.httpsServer.ports.containerPort }}
  type: ClusterIP
