apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-26"
spec:
  replicas: {{ .Values.primary-backend.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.primary-backend.image.repository }}:{{ .Values.primary-backend.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.primary-backend.image.pullPolicy }}
          imagePullSecrets:
            - name: {{ .Values.primary-backend.image.pullSecret }}
          ports:
            - name: {{ .Values.primary-backend.ports.name }}
              port: {{ .Values.primary-backend.ports.port }} 
              containerPort: {{ .Values.primary-backend.ports.containerPort }}
          resources:
            {{- toYaml .Values.primary-backend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: REDIS_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: RABBITMQ_URL
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: RESEND_API_KEY
            - name: JWT_SECRET_ACCESS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET_ACCESS
            - name: JWT_SECRET_REFRESH
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET_REFRESH
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: NODE_ENV
            - name: NEXT_PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: NEXT_PUBLIC_URL
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GITHUB_CLIENT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GOOGLE_CLIENT_SECRET
            
