apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  annotations:
    argocd.argoproj.io/sync-wave: "-23" 
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      name: {{ .Values.infraProvisioner.ports.name }}  
      port: {{ .Values.infraProvisioner.ports.port }}
      targetPort: {{ .Values.infraProvisioner.ports.containerPort }}
  type: ClusterIP