apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{.Chart.Name }}--serviceaccount"
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{.Chart.Name }}--role"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{.Chart.Name }}--rolebinding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{.Chart.Name }}--role"
subjects:
- kind: ServiceAccount
  name: "{{.Chart.Name }}--serviceaccount"

