apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend  
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default
  source:
    repoURL: https://github.com/Torque-Lab/cloud-infra-ops.git
    targetRevision: main
    path: apps/internal-charts/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
