apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}-{{ .Values.rabbitmq.rabbitmq_id }}-service
  annotations:
    argocd.argoproj.io/sync-wave: "-27"
spec:
  selector:
    app: {{ .Values.rabbitmq.name }}-{{ .Values.rabbitmq.rabbitmq_id }}
  ports:
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
  clusterIP: None