primary-backend:
    replicasCount: 1
    image:
        repository: ring0exec/primary-backend
        tag: bdefe0b1111240a6c0da15c35e9ba0d592b50bef
        pullPolicy: Always
        pullSecret: regcred
    ports:
        name: http
        port: 3001
        containerPort: 3001
    resources:
        requests:
            cpu: "50m"
            memory: "128Mi"
        limits:
            cpu: "500m"
            memory: "1Gi"
    autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 90