apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.name }}-{{ .Values.redis.redis_id }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.redis.syncWave | default "-25" | quote }}
spec:
  serviceName: "{{ .Values.redis.name }}-{{ .Values.redis.redis_id }}-service"
  replicas: {{ .Values.redis.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}-{{ .Values.redis.redis_id }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}-{{ .Values.redis.redis_id }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}-{{ .Values.redis.redis_id }}
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          ports:
            - containerPort: {{ .Values.redis.ports.containerPort }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.redis.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.redis.storage | default "1Gi" }}