
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}"
    spec:
      initContainers:
      - name: init-pgbouncer-config
        image: busybox
        command: ['sh', '-c', 'cp /config-temp/* /etc/pgbouncer/ && chmod 666 /etc/pgbouncer/*']
        volumeMounts:
        - name: config
          mountPath: /config-temp
          readOnly: true
        - name: config-volume
          mountPath: /etc/pgbouncer
      containers:
      - name: pgbouncer
        image: edoburu/pgbouncer
        ports:
        - containerPort: 6432
        command: ["pgbouncer", "/etc/pgbouncer/pgbouncer.ini"]
        env:
         - name: POSTGRES_HOST
           value: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}-service"
         - name: POSTGRES_PORT
           value: "{{ .Values.postgres.service.port | quote }}"
         - name: POSTGRES_DB
           valueFrom:
                secretKeyRef:
                  name: common-backend-secret
                  key: POSTGRES_DB
         - name: POSTGRES_USER
           valueFrom:
                secretKeyRef:
                  name: common-backend-secret
                  key: POSTGRES_USER
         - name: POSTGRES_PASSWORD
           valueFrom:
                secretKeyRef:
                  name: common-backend-secret
                  key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/pgbouncer
      volumes:
      - name: config
        configMap:
          name: "{{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}-ini-configmap"
          items:
            - key: pgbouncer.ini
              path: pgbouncer.ini
            - key: userlist.txt
              path: userlist.txt
          defaultMode: 0644 #base8
      - name: config-volum
        emptyDir: {}
          