apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-98"
spec:
  serviceName: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}-service"
  replicas: {{ .Values.postgres.replicasCount }}
  selector:
    matchLabels:
      app: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}"
    spec:
      containers:
        - name: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}"
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          ports:
            - containerPort: 5432
          securityContext:
            # allowPrivilegeEscalation: false
            # readOnlyRootFilesystem: true
            # capabilities:
            #   drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: common-backend-secret
        
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/rpgdata      
              name: data
     
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.postgres.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage | default "1Gi" }}
