
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}
    spec:
      containers:
      - name: pgbouncer
        image: edoburu/pgbouncer
        ports:
        - containerPort: 6432
        volumeMounts:
        - name: config
          mountPath: /etc/pgbouncer
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}-ini-configmap
          
