apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}
  labels:
    app: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}
spec:
  selector:
    app: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}
  ports:
    - port: {{ .Values.postgres.pgbouncer.service.port }}
      targetPort: {{ .Values.postgres.pgbouncer.service.targetPort }}
  clusterIP: None  #headless
