
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}
    spec:
      containers:
      - name: pgbouncer
        image: edoburu/pgbouncer
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: external-backend-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: external-backend-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: {{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}-service.default.svc.cluster.local

