apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}"
spec:
  serviceName: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}-service"
  replicas: {{ .Values.postgres.replicasCount }}
  selector:
    matchLabels:
      app: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}"
    spec:
      containers:
        - name: "{{ .Values.postgres.name }}-{{ .Values.postgres.db_id }}"
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          ports:
            - containerPort: 5432
          securityContext:
            # allowPrivilegeEscalation: false
            # readOnlyRootFilesystem: true
            # capabilities:
            #   drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          # this hard code is intentional tcp gateay do real auth
          env:
            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.POSTGRES_PASSWORD | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB | quote }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/rpgdata      
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage | default "2Gi" }}
        storageClassName: {{ .Values.postgres.storageClass | quote }}