{{- if .Values.postgres.backup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.postgres.db_id }}-backup
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: google/cloud-sdk:alpine
              command: ["/bin/sh", "/scripts/backup.sh"]
              env:
                - name: PGHOST
                  value:  "{{ .Values.postgres.name }}-pgbouncer-{{ .Values.postgres.db_id }}-service"
                - name: PGUSER
                  value: "{{ .Values.env.POSTGRES_USER }}"
                - name: PGDATABASE
                  value: "{{ .Values.env.POSTGRES_DB }}"
                - name: BUCKET_NAME
                  value: "{{ .Values.postgres.backup.bucketName }}"
                - name: CONTROL_PLANE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: backup-secrets
                      key: CONTROL_PLANE_TOKEN
              volumeMounts:
                - name: backup-script
                  mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
            - name: backup-script
              configMap:
                name: postgres-backup-scripts
                defaultMode: 0755
{{- end -}}