apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.postgres.db_id }}--serviceaccount
  namespace:

{{- if .Values.postgres.backup.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Values.postgres.db_id }}--role
 
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.postgres.db_id }}--rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Values.postgres.db_id }}--role
subjects:
- kind: ServiceAccount
  name: {{.Values.postgres.db_id }}--serviceaccount
  namespace: 
{{- end }}
