{{- if .Values.postgres.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.postgres.db_id }}-backup
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: google/cloud-sdk:alpine
              command: ["/bin/sh", "/scripts/backup.sh"]
              env:
                - name: PGHOST
                  value: {{ .Values.postgres.serviceName }}
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: password
                - name: PGDATABASE
                  value: {{ .Values.postgres.database }}
                - name: BUCKET_NAME
                  value: {{ .Values.backup.bucketName }}
                - name: CONTROL_PLANE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: backup-secrets
                      key: CONTROL_PLANE_TOKEN
              volumeMounts:
                - name: backup-script
                  mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
            - name: backup-script
              configMap:
                name: postgres-backup-scripts
                defaultMode: 0755
{{- end }}           

